// AUTH
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_REGISTER_USER_REQUEST = 'AUTH_REGISTER_USER_REQUEST';
export const AUTH_REGISTER_USER_FAILURE = 'AUTH_REGISTER_USER_FAILURE';
export const AUTH_REGISTER_USER_SUCCESS = 'AUTH_REGISTER_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_INVALIDATE_TOKEN = 'AUTH_INVALIDATE_TOKEN';
export const AUTH_CLEAN_STATUS_TEXT = 'AUTH_CLEAN_STATUS_TEXT';

// MODALS
export const SHOW_NEW_ACCOUNT_MODAL = 'SHOW_NEW_ACCOUNT_MODAL';
export const HIDE_NEW_ACCOUNT_MODAL = 'HIDE_NEW_ACCOUNT_MODAL';
export const SHOW_WITHDRAW_REQUEST_MODAL = 'SHOW_WITHDRAW_REQUEST_MODAL';
export const HIDE_WITHDRAW_REQUEST_MODAL = 'HIDE_WITHDRAW_REQUEST_MODAL';
export const SHOW_ACCOUNT_ADDRESS_MODAL = 'SHOW_ACCOUNT_ADDRESS_MODAL';
export const HIDE_ACCOUNT_ADDRESS_MODAL = 'HIDE_ACCOUNT_ADDRESS_MODAL';
export const SHOW_NEW_LOAN_MODAL = 'SHOW_NEW_LOAN_MODAL';
export const HIDE_NEW_LOAN_MODAL = 'HIDE_NEW_LOAN_MODAL';
export const SHOW_CHANGE_PASSWORD_MODAL = 'SHOW_CHANGE_PASSWORD_MODAL';
export const HIDE_CHANGE_PASSWORD_MODAL = 'HIDE_CHANGE_PASSWORD_MODAL';

// USER ACCOUNT
export const DATA_FETCH_USER_ACCOUNT_DATA_REQUEST =
  'DATA_FETCH_USER_ACCOUNT_DATA_REQUEST';
export const DATA_RECEIVE_USER_ACCOUNT_DATA = 'DATA_RECEIVE_USER_ACCOUNT_DATA';
export const DATA_FETCH_USER_ACCOUNT_DATA_FAILURE =
  'DATA_FETCH_USER_ACCOUNT_DATA_FAILURE';
export const USER_ACCOUNT_SET_KYC_APPLIED = 'USER_ACCOUNT_SET_KYC_APPLIED';

// ACCOUNT COINS
export const DATA_FETCH_ACCOUNT_COINS_DATA_REQUEST =
  'DATA_FETCH_ACCOUNT_COINS_DATA_REQUEST';
export const DATA_RECEIVE_ACCOUNT_COINS_DATA =
  'DATA_RECEIVE_ACCOUNT_COINS_DATA';
export const DATA_FETCH_ACCOUNT_COINS_DATA_FAILURE =
  'DATA_FETCH_ACCOUNT_COINS_DATA_FAILURE';
// INDIVIDUAL ACCOUNT
export const DATA_FETCH_ACCOUNT_DATA_REQUEST =
  'DATA_FETCH_ACCOUNT_DATA_REQUEST';
export const DATA_RECEIVE_ACCOUNT_DATA = 'DATA_RECEIVE_ACCOUNT_DATA';
export const DATA_FETCH_ACCOUNT_DATA_FAILURE =
  'DATA_FETCH_ACCOUNT_DATA_FAILURE';

// ADD ACCOUNT
export const DATA_ADD_ACCOUNT_SUCCESS = 'DATA_ADD_ACCOUNT_SUCCESS';
export const DATA_ADD_ACCOUNT_FAILURE = 'DATA_ADD_ACCOUNT_FAILURE';

// CRYPTO WITHDRAWAL
export const DATA_CRYPTO_WITHDRAWAL_REQUEST = 'DATA_CRYPTO_WITHDRAWAL_REQUEST';
export const DATA_CRYPTO_WITHDRAWAL_SUCCESS = 'DATA_CRYPTO_WITHDRAWAL_SUCCESS';
export const DATA_CRYPTO_WITHDRAWAL_FAILURE = 'DATA_CRYPTO_WITHDRAWAL_FAILURE';

// NEW LOAN
export const APPLY_NEW_LOAN_REQUEST = 'APPLY_NEW_LOAN_REQUEST';
export const APPLY_NEW_LOAN_FAILURE = 'APPLY_NEW_LOAN_FAILURE';
export const APPLY_NEW_LOAN_SUCCESS = 'APPLY_NEW_LOAN_SUCCESS';
export const SET_NEW_LOAN_USER_APPLIED_VALUE = 'SET_NEW_LOAN_USER_APPLIED_VALUE';
// CRYPTO PRICE
export const WANTED_COINS = ['bitcoin', 'ethereum'];
export const DATA_FETCH_COINS_PRICE_DATA_REQUEST =
  'DATA_FETCH_COINS_PRICE_DATA_REQUEST';
export const DATA_RECEIVE_COINS_PRICE_DATA = 'DATA_RECEIVE_COINS_PRICE_DATA';
export const DATA_FETCH_COINS_PRICE_DATA_FAILURE =
  'DATA_FETCH_COINS_PRICE_DATA_FAILURE';

// LOAN APPLICATIONS
export const FETCH_LOAN_APPLICATIONS_REQUEST = 'FETCH_LOAN_APPLICATIONS_REQUEST';
export const FETCH_LOAN_APPLICATIONS_SUCCESS = 'FETCH_LOAN_APPLICATIONS_SUCCESS';
export const FETCH_LOAN_APPLICATIONS_FAILURE = 'FETCH_LOAN_APPLICATIONS_FAILURE';

// UI
export const DATA_PICK_NEW_ACCOUNT = 'DATA_PICK_NEW_ACCOUNT';
export const NAV_MENU_TOGGLE = 'NAV_MENU_TOGGLE';
export const SIDE_MENU_TOGGLE = 'SIDE_MENU_TOGGLE';

// INPUTS
export const SET_LOANED_AMMOUNT_VALUE = 'SET_LOANED_AMMOUNT_VALUE';
