// AUTH
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_REGISTER_USER_REQUEST = 'AUTH_REGISTER_USER_REQUEST';
export const AUTH_REGISTER_USER_FAILURE = 'AUTH_REGISTER_USER_FAILURE';
export const AUTH_REGISTER_USER_SUCCESS = 'AUTH_REGISTER_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_INVALIDATE_TOKEN = 'AUTH_INVALIDATE_TOKEN';

// MODALS
export const SHOW_NEW_ACCOUNT_MODAL = 'SHOW_NEW_ACCOUNT_MODAL';
export const HIDE_NEW_ACCOUNT_MODAL = 'HIDE_NEW_ACCOUNT_MODAL';

// ACCOUNT COINS
export const DATA_FETCH_ACCOUNT_COINS_DATA_REQUEST =
  'DATA_FETCH_ACCOUNT_COINS_DATA_REQUEST';
export const DATA_RECEIVE_ACCOUNT_COINS_DATA =
  'DATA_RECEIVE_ACCOUNT_COINS_DATA';
export const DATA_FETCH_ACCOUNT_COINS_DATA_FAILURE =
  'DATA_FETCH_ACCOUNT_COINS_DATA_FAILURE';
// INDIVIDUAL ACCOUNT
export const DATA_FETCH_ACCOUNT_DATA_REQUEST =
  'DATA_FETCH_ACCOUNT_DATA_REQUEST';
export const DATA_RECEIVE_ACCOUNT_DATA = 'DATA_RECEIVE_ACCOUNT_DATA';
export const DATA_FETCH_ACCOUNT_DATA_FAILURE =
  'DATA_FETCH_ACCOUNT_DATA_FAILURE';

// ADD ACCOUNT
export const DATA_ADD_ACCOUNT_SUCCESS = 'DATA_ADD_ACCOUNT_SUCCESS';
export const DATA_ADD_ACCOUNT_FAILURE = 'DATA_ADD_ACCOUNT_FAILURE';

// UI
export const DATA_PICK_NEW_ACCOUNT = 'DATA_PICK_NEW_ACCOUNT';
